### ISSUE TITLE
net: bind to internal host, return external host

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/multiserver#13]
so i'm working on the ButtCloud infrastructure ([butt](https://github.com/buttcloud/butt)), i finally figured out a bug that's kept me stuck on that front for over a week.

it seems i need a way for the scuttlebot server to bind to a host like 0.0.0.0 (internal to the Docker Swarm service, which is automatically available to other internal services and exported via an ingress router to the external internet), but then advertise a different public host like `party.butt.nz` (like when publishing invites and things).

**Comment by ahdinosaur** [comment]
for now i made a custom `scuttlebot` plugin:

```js
module.exports = function address (server, conf) {
  const getInternalAddress = server.getAddress

  function getExternalAddress () {
    if (conf.externalHost) {
      const key = conf.keys.public
      const { port } = conf
      const host = conf.externalHost
      return toAddress({ key, host, port })
    }
    return getInternalAddress()
  }

  server.getAddress = getExternalAddress
}

module.exports.init = module.exports

function toAddress ({ key, host, port }) {
  const net = [
    'net',
    host,
    port
  ].join(':')

  const shs = [
    'shs',
    toBase64(key)
  ].join(':')

  return net + '~' + shs
}

function toBase64 (s) {
  if (isString(s)) return s
  else s.toString('base64') //assume a buffer
}

function isString (s) {
  return typeof s === 'string'
}
```

**Comment by dominictarr** [comment]
I must say I disapprove of `  server.getAddress = getExternalAddress` this is a monkey patch, it's unclear what implications this could have. You are not the only one who might want to put sbot inside docker, so lets solve this problem _right_.

so does it work if you just bind to `0.0.0.0`? trying to remember why we just don't do that?

**Comment by ahdinosaur** [comment]
> I must say I disapprove of server.getAddress = getExternalAddress this is a monkey patch, it's unclear what implications this could have. You are not the only one who might want to put sbot inside docker, so lets solve this problem _right_.

yeah for sure, i made this issue so we could solve it _right_, my code above is a HACK. :monkey: 

> so does it work if you just bind to `0.0.0.0`? trying to remember why we just don't do that?

yes that works, i'm happy if we do that. is also what is proposed in https://github.com/ssbc/ssb-viewer/issues/4.

**Comment by dominictarr** [comment]
I'm trying to recall _why we don't_ do that already... I _vaguely recall_ that listening on '0.0.0.0' makes it not work for ipv6... but maybe there is another way... even if it's just making two servers, one listening on `0.0.0.0` and the other on whatever the ipv6 equivalent is. /cc @soapdog

**Comment by arj03** [comment]
This should be solved now with the external keyword inside connections.
