### ISSUE TITLE
remove footguns, make it hard to create insecure configurations

### ISSUE THREAD

**Issue by dominictarr** [ssbc/multiserver#26]
Today I gave a talk on designing for security. One of my main messages was "don't make it configurable" or at least "don't make it easier to have an insecure configuration"

I remembered that multiserver noauth is a potential problem here.
It would be easy to set `net~noauth` and it would be faster! except now anyone can connect to you, and tell you what to do, if you have noauth set.

It's not a responsible design to expect them to understand not to use `noauth` with a network.
They should have to _explicitly_ enable the footgun. 

My idea to approach this: first make sure all the plugins set an address property consistently.
then, have `noauth` take an address config option, and refuse connections that do not have the correct address. This means to enable noauth, you have to set the address twice!

```
ws: [{scope: 'device', port: 8989, transform: { name: 'noauth', address: 'ws://localhost:8989' }}]
```
or something like that. We don't have a way to specify configuration for transforms yet.

I have this about half coded

thoughts? @arj03 @regular

**Comment by regular** [comment]
@dominictarr I think that's a great idea! A remark from an accessibility standpoint: I'd prefer something more inconvenient, more explicit and easier understood internationally than `foorgun` as the name for the manual override. I don't remember where I saw it, but in some server you have to set the option `--i-want-to-be-a-botnet` and I really liked that. How bout `i_dont_care_about_privacy_and_security` as the name for the option?

**Comment by dominictarr** [comment]
@arj03 it's a human factors approach. like, if your car dings if a door is still open, that makes it more secure, because then you remember to close the door.

I'm definitely open to other ways a safely factor could be enabled.
detecting whether it's on a publically accessable address would work too, but adding knowledge of all the transport plugins into noauth would make it too coupled, and that code could have bugs too.

Hmm, is it enough to have noauth refuse to run scopes other than `device`?
that said - when running ws in a device scope, actually any website you have open in a tab can create a websocket to localhost, so there should be an explicit check for the correct domain... It doesn't matter much if we only have encrypted connections.

but there is dns rebinding, which gets around CORS:
https://blog.hacker.af/how-your-ethereum-can-be-stolen-using-dns-rebinding
and anyway, websockets work cross-origin by default:
https://stackoverflow.com/questions/20274902/how-may-a-web-page-that-is-loaded-via-https-connect-to-a-websocket-server-runnin

if some one has downloaded a program and run it in user space, there really isn't much we can do.. but just getting someone to open a website is much easier
