### ISSUE TITLE
Create a transport option for the I2P network.

### ISSUE THREAD

**Issue by metamarcdw** [ssbc/multiserver#31]
I2P is an anonymous overlay network similar to Tor, but with different security and decentralization trade-offs. It is an extremely mature project and would be very desireable to have available.

https://geti2p.net

**Comment by dominictarr** [comment]
Yes definitely, we do have tor support - and ssb isn't tied to any particular way of networking, so we are keen to have support everything, basically. I would definitely be happy to assist someone who wanted to add i2p with any scuttlebutt questions they may have.
