### ISSUE TITLE
Unix socket with default path exposes username over network

### ISSUE THREAD

**Issue by christianbundy** [ssbc/multiserver#39]
I saw in %94G9B4MPIbhQynNlCApdn88PlT73/PE9l/jKmOsxy84=.sha256 that we're broadcasting the unix socket over UDP, which exposes our username to all network peers. I'd love to avoid this, if possible. Potential solutions:

1. Don't broadcast unix sockets (?)
2. Use a temporary socket with `mktemp`

    ```console
    $ mktemp
    /tmp/tmp.NrzUtkX6jl
    ```

**Comment by arj03** [comment]
I think is some naming confusion. Luckily the ssb-config [README](https://github.com/ssbc/ssb-config#connections) is quite clear. So use device scope instead of local.

**Comment by dominictarr** [comment]
public/private oh and local are quite confusing here.
why didn't we call it "device", "wifi", "internet" ?

**Comment by arj03** [comment]
Yeah, I made the socket code more defensive about potential problems in this [PR](https://github.com/ssbc/multiserver/pull/40)

**Comment by christianbundy** [comment]
:taco:
