### ISSUE TITLE
Why does noauth need the public key?

### ISSUE THREAD

**Issue by staltz** [ssbc/multiserver#56]
I see [this commit](https://github.com/ssbc/multiserver/commit/2b50597fa29d8076973c37caeb41ee87e5fb9d62), but I don't understand what's the context around that commit. What breaks if we use empty strings instead?

My context: given that I'm using trusted transports (e.g. react native's "bridge" which is closed to other applications in the OS, and obviously closed to remote actors), I believe I don't need the public key, hence I could save the cost of using FS APIs on the frontend looking for `secret`, but the way noauth plugin is built requires me to pass it a public key.

**Comment by staltz** [comment]
cc @arj03

**Comment by arj03** [comment]
@staltz its quite a while since I made that commit but as far as I remember its because muxrpc needs the id of the remote peer [here](https://github.com/ssbc/secret-stack/blob/d48649261455b0a41955de0874428a41b41148d3/core.js#L182).

**Comment by dominictarr** [comment]
that's correct. it needs the public key to show who it's authorized as

**Comment by staltz** [comment]
Okay, got my question answered. Thanks!

**Comment by staltz** [comment]
Interesting, I learned something: client-side, `noauth` does *not* need the public key. That line where `stream.remote` is read, happens only server-side, so as long as `noauth` on the server is setup with the public key, it works.

This is good news because my initial guess was correct and I can actually remove the key lookup client-side:

>  I believe I don't need the public key, hence I could save the cost of using FS APIs on the frontend looking for secret, but the way noauth plugin is built requires me to pass it a public key.
