### ISSUE TITLE
Address format

### ISSUE THREAD

**Issue by arj03** [ssbc/multiserver#58]
Looking at: https://github.com/ssbc/multiserver#address-format I see that net is specified as net:, while wss is specified as wss://? Seems as if both should be specified the same way, so `wss:wx.larpa.net~shs:DTNmX+4SjsgZ7xyDh5xxmNtFqa6pWi5Qtw7cE8aR9TQ=`, instead of `wss://wx.larpa.net~shs:DTNmX+4SjsgZ7xyDh5xxmNtFqa6pWi5Qtw7cE8aR9TQ=`?

**Comment by christianbundy** [comment]
+1, I'd strongly support these addresses being treated as URIs (and if it's a location, using `://` instead of `:`).

**Comment by arj03** [comment]
Also this repo https://github.com/ssbc/multiserver-address could REALLY use an example or two :-)

**Comment by staltz** [comment]
Agreed

**Comment by arj03** [comment]
It appears that both : and :// are valid. I added some examples to the repo.
