### ISSUE TITLE
why do multiserver addresses not include the "full" public key?

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/multiserver#9]
i notice that multiserver addresses, like

```txt
net:wx.larpa.net:8008~shs:DTNmX+4SjsgZ7xyDh5xxmNtFqa6pWi5Qtw7cE8aR9TQ=
```

truncate the "full" public key to 

```txt
DTNmX+4SjsgZ7xyDh5xxmNtFqa6pWi5Qtw7cE8aR9TQ=
```

instead of

```txt
@DTNmX+4SjsgZ7xyDh5xxmNtFqa6pWi5Qtw7cE8aR9TQ=.ed25519
```

as is the format used everywhere else.

for more context, this became annoying when i wanted to write a jinja template for file managed by Salt Stack, where i had access to the values in `~/.ssb/secret` but had no ability to truncate the public key as required to create a multiserver address in the template.

i've now worked around this problem, but i still was wondering on the thinking behind it, i don't know much about how important it is to have the curve in the key, as i think this is also implied when saying `shs`.

**Comment by dominictarr** [comment]
well, it's because shs isn't configurable and _only_ supports ed25519 keys anyway, so putting that in there wouldn't do anything. It's trying to be as generic as possible, shs and multiserver don't have to be used with ssb.

**Comment by ahdinosaur** [comment]
cool!
